export const florestAudioCard = new Audio('./assets/audio/Floresta.wav')
export const CafeteriaAudioCard = new Audio('./assets/audio/Cafeteria.wav')
export const ChuvaAudioCard = new Audio('./assets/audio/Chuva.wav')
export const LareiraAudioCard = new Audio('./assets/audio/Lareira.wav')
export const none = document.querySelector('.none')